version: '3.7'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 4000:80
    user: '0'
    volumes:
      - ./flask:/flask
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - FLASK_APP=/app/pathway
      - FLASK_ENV=development
    devices:
      - "/dev/dri:/dev/dri"
    network_mode: "host"
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
