version: '3.7'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile_main
    # image: deep_green:latest
    ports:
        - 4000:80
    user: '0'
    volumes:
      - ./assets:/app/assets
      - ./js:/app/js
      - ./css:/app/css
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    devices:
      - "/dev/dri:/dev/dri"
    network_mode: "host"
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
